exclude: ^scripts
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black
        pass_filenames: true
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort
        pass_filenames: true
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: poetry run mypy
        pass_filenames: true
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: poetry run flake8 --ignore=W503
        pass_filenames: true
        language: system
        files: '\.py$'
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        name: Run pydocstyle
        args:
          - --convention=google
            #- --add-ignore=D100,D102,D103,D104,D105,D107,D202,D205,D400,D401
        exclude: _test.py$
        pass_filenames: true
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint -j 0 src
        pass_filenames: false
        always_run : true
        language: system
        files: '\.py$'
